### ISSUE TITLE
404 Not Found

### ISSUE THREAD

**Issue by etienne-herlaut-cko** [pavi2410/html-preview-action#12]
I am trying to use your tool to display my test result.
I like the PR comment functionality so I am using your `v1a`.
It passes the `Publish test results` step but then I get a 404 when clicking on the link:

![image](https://user-images.githubusercontent.com/72391505/101999474-b2cab480-3cdd-11eb-82cd-dbe7714226e8.png)

Any pointers?

Here is my workflow:
```
env:
  PYTHON: /usr/bin/python3
  WORKING_DIR: /home/runner/work/surface-tmp/surface-tmp
  VENV: /home/runner/work/surface-tmp/surface-tmp/.env/bin
  PYSPARK_PYTHON: python3
  PYSPARK_DRIVER_PYTHON: python3

name: Surface

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
      - name: Test
        run: |
          ${PYTHON} -m venv .env
          ${VENV}/pip install -r ${WORKING_DIR}/requirements.txt
          ${VENV}/python test_report.py --open_browser False
      - name: Publish test results
        id: html_preview
        uses: pavi2410/html-preview-action@v1a
        with:
          msg: 'Click here to open test result in browser'
          html_file: 'reports/surface-test-report.html'
```
